# Generated by Django 4.1.2 on 2022-10-21 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPrivate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_id", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=200)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=40)),
                ("profile_img_url", models.CharField(max_length=400)),
                ("profile_message", models.CharField(max_length=400)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userprivate",
                    ),
                ),
            ],
        ),
    ]
